### ISSUE TITLE
Direct link to the dashboard from the user dropdown

### ISSUE THREAD

**Issue by iamdarkle** [flarum-com/flarum-org#16]
Maybe I'm missing it, but is there any way to access the Dashboard from flarum.org other than directly via URL/buttons in the extension discovery?

If not, adding a link to it would be quite useful:

![image](https://github.com/flarum-com/flarum-org/assets/15818451/9e0431b4-103e-45dc-a1bf-7de657aa79e2)

**Comment by luceos** [comment]
What do you mean from the extension discovery @iamdarkle, that menu is available on all pages including the homepage?

**Comment by iamdarkle** [comment]
Yeah, that menu is available everywhere. That's why in the image above, I added the "Dashboard" link as an example to fix it.

![image](https://github.com/flarum-com/flarum-org/assets/15818451/623b821c-030d-4745-b86e-0e86d03ad17c)

Regarding the discovery, I was referring to this button here in the premium extensions, which does allow you to access the dashboard. I think it's currently the only way to access it via UI.

**Comment by luceos** [comment]
Oh I see. Yeah that link exists under the team instead of the user.


![image](https://github.com/flarum-com/flarum-org/assets/504687/acaf6ddf-736d-4de0-841b-05c3957f1548)

Having it not under the user might be confusing; unless you don't have a team 🤔 Which might be the case for you.

I guess it makes more sense to have it under the user in fact.

**Comment by iamdarkle** [comment]
You're right, I haven't created any teams yet, so I didn't see that. I know it's a bit off-topic 😅 but I'm curious what the teams are for, is it mainly for the development of premium extensions?

**Comment by luceos** [comment]
The dashboard link was moved.
